import { beforeEach, describe, expect, it, vi } from "vitest";
const { loadSkillConfig } = vi.hoisted(() => ({ loadSkillConfig: vi.fn() }));
vi.mock("../src/config.js", () => ({ loadSkillConfig, getEnvVar: () => undefined }));
import { buildSkillContextParityDriftSignatureRequest, evaluateSkillContextParityDriftSignature, registerSkillContextParityDriftSignatureDiagnosticsFunction } from "../src/functions/skill-context-parity-drift-signature.js";

function config() { return { contextEnabled: true }; }
function shape(overrides: Record<string, unknown> = {}) { return { success:true,enabled:true,applied:false,state:"stable_consistent",reasonCodes:["stable_consistency_shaped"],sourceSamplingMode:"sequential_double_sample_non_atomic",shapeAvailable:true,scopeTriggerAttempted:true,scopeTriggerSucceeded:true,scopeResultParsed:true,laneShape:"none",stageSpan:"none",stageAttributionPresent:false,parityOutcomePresent:false,...overrides }; }
function sdk() { const functions=new Map<string,(v:unknown)=>Promise<unknown>>(); const requests: unknown[]=[]; let next: (()=>Promise<unknown>)|undefined; return {functions,requests,set:(f:()=>Promise<unknown>)=>next=f,registerFunction:(id:string,fn:(v:unknown)=>Promise<unknown>)=>functions.set(id,fn),trigger:async(v:unknown)=>{requests.push(v);return next!();}}; }
describe("skill context parity drift signature diagnostics",()=>{ let mock:ReturnType<typeof sdk>; const input={project:"/repo",overallBudget:1,usedTokens:0,selectedBlockCount:0}; beforeEach(()=>{loadSkillConfig.mockReset();loadSkillConfig.mockReturnValue({contextEnabled:false});mock=sdk();registerSkillContextParityDriftSignatureDiagnosticsFunction(mock as never);});
it("gates before validation and builds fresh exact requests",async()=>{const run=(v:unknown)=>mock.functions.get("mem::skill-context-parity-drift-signature-diagnostics")!(v);await expect(run(Symbol("x"))).resolves.toMatchObject({state:"disabled",signature:null});expect(mock.requests).toEqual([]);const a=buildSkillContextParityDriftSignatureRequest({...input,agentId:" agent "});const b=buildSkillContextParityDriftSignatureRequest({...input,agentId:" agent "});expect(a).toEqual({function_id:"mem::skill-context-parity-drift-shape-diagnostics",payload:{...input,agentId:" agent "}});expect(a.payload).not.toBe(b.payload);});
it("uses fixed signatures and fails closed",async()=>{expect(evaluateSkillContextParityDriftSignature({state:"observed_drift",laneShape:"parity_only",stageSpan:"none",stageAttributionPresent:false,parityOutcomePresent:true})).toBe("v1:observed_drift:parity_only:none");loadSkillConfig.mockReturnValue(config());mock.set(async()=>shape());const run=(v:unknown)=>mock.functions.get("mem::skill-context-parity-drift-signature-diagnostics")!(v);await expect(run(input)).resolves.toMatchObject({success:true,signature:"v1:stable_consistent:none:none"});mock.set(async()=>({...shape(),laneShape:"direct_drift",stageSpan:"none"}));await expect(run(input)).resolves.toMatchObject({reasonCodes:["invalid_shape_result"]});});
});
